#!/usr/bin/env python3
"""Guardrail Repo Scanner (CON-2014) — full-repo insertion-point scan + PR.

Clones a repository, detects all unguarded data-transfer points using the
UniFAI insertion-point scanner, inserts ``guardrail_check()`` stubs into the
source files, commits to a new branch, and opens a pull request.

Unlike the existing ``repo_scan.py`` (which scans for SBOM/vuln violations via
the MCP pipeline), this script focuses exclusively on guardrail stub coverage.
It uses NO MCP server — it runs the scanner locally and applies stubs directly.

Usage::

    python scripts/gr_repo_scan.py \\
        --repo owner/repo \\
        --branch main \\
        --tenant-id <your-tenant-id>

    # Or scan a local clone (skip the clone step)
    python scripts/gr_repo_scan.py \\
        --local-path /path/to/repo \\
        --tenant-id <your-tenant-id> \\
        --no-pr

Environment variables::

    SCM_PROVIDER         — github | bitbucket | gitlab  (default: github)
    SCM_ACCESS_TOKEN     — GitHub PAT / Bitbucket app password / GitLab PAT
    GR_TENANT_ID         — Tenant ID (overridden by --tenant-id)
    GR_COMPANY_ID        — Company ID (optional)
    LINEAJE_PAT          — Lineaje PAT for GR service auth + Data Service upload

Exit codes::

    0 — scan complete (violations found + PR opened, or no violations)
    1 — runtime error
    2 — configuration error
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

# ── Path setup so we can import insertion_point_scanner from parent dir ───────
_HERE = Path(__file__).resolve().parent
_PARENT = _HERE.parent
for _p in (_HERE, _PARENT):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from scm_client import create_scm_client  # noqa: E402
from insertion_point_scanner import (  # noqa: E402
    scan_project, _import_hint, safe_prefix_insert_index, validate_python_source,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
_logger = logging.getLogger("gr_repo_scan")

# ── Constants ─────────────────────────────────────────────────────────────────

_STUB_BRANCH_PREFIX = "unifai/guardrail-stubs"
_PR_TITLE_TEMPLATE = "chore: add UniFAI guardrail stubs ({count} insertion point(s))"
_COMMENT_MARKER = "<!-- unifai-gr-repo-scan -->"
_BOT_PR_BODY_TEMPLATE = """\
{marker}
## UniFAI Guardrail Stub Insertion

This PR was generated automatically by `gr_repo_scan.py` (CON-2014).

**{count} unguarded insertion point(s)** were detected across **{files} file(s)**:

{table}

{components_section}
### What was inserted
For each detected boundary crossing a `guardrail_check()` call was added.
The stub forwards data to the Lineaje GR service for policy evaluation
(PII redaction, content filtering, etc.) and returns the transformed payload.

### Setup
```bash
pip install httpx
# Set in your environment:
export GR_SERVICE_URL=http://localhost:8001
export GR_TENANT_ID={tenant_id}
```

> Generated by [UniFAI Guardrail Scanner](https://lineaje.com)
"""

_COMPONENTS_SECTION_TEMPLATE = """\
### AI Components Discovered ({count})

| Name | Type | Framework | Source File |
|---|---|---|---|
{rows}

"""


# ── Git helpers ───────────────────────────────────────────────────────────────

def _git_clone(repo: str, branch: str, dest: str, token: str, provider: str) -> None:
    if provider == "github":
        url = f"https://x-access-token:{token}@github.com/{repo}.git"
    elif provider == "bitbucket":
        user = os.environ.get("SCM_USERNAME", "x-token-auth")
        url = f"https://{user}:{token}@bitbucket.org/{repo}.git"
    else:
        url = f"https://oauth2:{token}@gitlab.com/{repo}.git"

    _logger.info("Cloning %s@%s …", repo, branch)
    subprocess.run(
        ["git", "clone", "--depth=1", "--branch", branch, url, dest],
        check=True,
        capture_output=True,
    )


def _git_head_sha(clone_dir: str) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=clone_dir,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def _write_file(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ── Stub application ──────────────────────────────────────────────────────────

def _apply_stubs(candidates: list, clone_dir: str, skip_unsafe: bool = True) -> dict[str, str]:
    """Apply stub insertions to files in clone_dir. Returns {rel_path: new_content}.

    skip_unsafe=True (default) drops any candidate the scanner itself marked
    safe_to_insert=False before doing anything else — this was previously
    NOT enforced here at all (every candidate passed in was applied
    regardless of the scanner's own confidence, unlike every other write
    path in this codebase). Pass skip_unsafe=False for a caller that has
    already made its own informed choice to include unsafe candidates (see
    scripts/apply_gr_stubs_local.py's ``--include-unsafe`` flag) — otherwise
    that opt-in would be silently defeated by this function re-filtering
    what the caller explicitly asked to keep.

    Shares its safety-critical logic — loader/import placement that avoids
    landing above a module docstring or a `from __future__ import` line, and
    whole-file compile() validation for Python — with
    guardrail_stub_insertion.py's write path via
    insertion_point_scanner.safe_prefix_insert_index() /
    validate_python_source() (Independent Code Review's "two unconverged
    write paths" finding, docs/CODE_REVIEW_ADDENDUM_2026-08-10.md recommended
    fix #4). The two paths still differ in what gets inserted — this script
    scans for every unguarded insertion point across a whole repo with no
    violation input at all, guardrail_stub_insertion.py only instruments
    candidates an actual evaluator violation lands on — that's a genuine,
    intentional difference in scope, not drift. What's shared now is "is
    this candidate even insertable" and "is the result still valid Python",
    the two questions previously answered by independently maintained copies
    that had silently diverged (this path had neither the safe_to_insert
    filter nor any syntax validation at all until this fix).
    """
    by_file: dict[str, list] = {}
    for c in candidates:
        if skip_unsafe and not getattr(c, "safe_to_insert", True):
            _logger.info(
                "Skip %s:%s [%s] unsafe — %s", c.file, c.line, c.insertion_point, c.skip_reason,
            )
            continue
        by_file.setdefault(c.file, []).append(c)

    changed: dict[str, str] = {}
    for rel_path, hits in by_file.items():
        abs_path = os.path.join(clone_dir, rel_path)
        if not os.path.isfile(abs_path):
            _logger.warning("File not found in clone: %s — skipping", rel_path)
            continue

        lines = _read_file(abs_path).splitlines(keepends=True)
        ext = Path(rel_path).suffix

        # Sort hits descending by line so inserting doesn't shift earlier offsets
        sorted_hits = sorted(hits, key=lambda h: h.line, reverse=True)

        import_line = _import_hint(ext) + "\n"
        needs_import = False

        for hit in sorted_hits:
            # 1-based line; insert_after=True (result/lhs patterns, e.g.
            # db_read) must land AFTER the line that assigns the variable
            # the stub references — inserting before is a NameError.
            idx = max(0, hit.line if getattr(hit, "insert_after", False) else hit.line - 1)
            stub_line = hit.proposed_stub + "\n"
            lines.insert(idx, stub_line)
            needs_import = True

        if needs_import:
            # Skip re-inserting the inlined gr_check()/GRBlockedError block
            # if a prior run already added it — harmless shadowing for
            # Python, but a duplicate top-level function/class declaration
            # is a real SyntaxError for JS/TS.
            _marker = "function gr_check(" if ext.lower() in (".js", ".jsx", ".ts", ".tsx") else "def gr_check("
            if _marker not in "".join(lines):
                lines.insert(safe_prefix_insert_index(lines), import_line)

        new_content = "".join(lines)

        # Whole-file syntax validation — Python only, compile() has no
        # equivalent for JS/TS/Go/Java here, so those still ship without a
        # validated-result guarantee (documented limitation, not silently
        # assumed safe).
        if ext.lower() == ".py":
            syntax_err = validate_python_source(new_content, abs_path)
            if syntax_err:
                _logger.warning(
                    "Skip %s — would produce invalid syntax (%s), likely the multi-line-call "
                    "insert_after scanner bug; left untouched", rel_path, syntax_err,
                )
                continue

        changed[rel_path] = new_content

    return changed


# ── Markdown helpers ──────────────────────────────────────────────────────────

def _make_table(candidates: list) -> str:
    by_file: dict[str, list] = {}
    for c in candidates:
        by_file.setdefault(c.file, []).append(c)

    rows = ["| File | Line | Insertion Point | Description |",
            "|---|---|---|---|"]
    for rel_path, hits in sorted(by_file.items()):
        for h in sorted(hits, key=lambda x: x.line):
            rows.append(f"| `{rel_path}` | {h.line} | `{h.insertion_point}` | {h.description} |")
    return "\n".join(rows)


def _make_components_section(components: list[dict]) -> str:
    if not components:
        return ""
    rows = [
        f"| `{c['name']}` | {c['type']} | {c.get('framework') or '—'} | `{c.get('source_file') or '—'}` |"
        for c in sorted(components, key=lambda x: (x["type"], x["name"]))
    ]
    return _COMPONENTS_SECTION_TEMPLATE.format(
        count=len(components),
        rows="\n".join(rows),
    )


# ── Component discovery + upload ──────────────────────────────────────────────

def _discover_components(clone_dir: str) -> tuple[list[dict], Any]:
    """Run Pass 1 static analysis on the cloned repo. Returns (component_list, graph)."""
    try:
        from pipeline.discovery.discovery import run_static_analysis
        _skip_dirs = {"node_modules", ".git", "__pycache__", "venv", ".venv",
                      "dist", "build", ".tox", ".mypy_cache"}
        _scan_exts = {".py", ".js", ".ts", ".jsx", ".tsx", ".java"}
        _root = Path(clone_dir)
        _file_tuples: list[tuple[str, str]] = []
        for _p in _root.rglob("*"):
            if any(part in _skip_dirs for part in _p.parts):
                continue
            if _p.is_file() and _p.suffix.lower() in _scan_exts:
                try:
                    _rel = str(_p.relative_to(_root))
                    _file_tuples.append((_rel, _p.read_text(encoding="utf-8", errors="replace")))
                except Exception:
                    pass
            if len(_file_tuples) >= 200:
                break

        if not _file_tuples:
            return [], None

        _, graph = run_static_analysis(_file_tuples)
        _type_to_doc_type = {
            "model": "aimodel", "agent": "aiagent",
            "mcp_server": "mcpserver", "mcp_client": "mcpserver",
            "rag": "rag", "package": "package",
            "skill": "skill", "agent_config": "agent_config",
        }
        components = [
            {
                "name": c.name,
                "type": c.component_type.value,
                "doc_type": _type_to_doc_type.get(c.component_type.value, c.component_type.value),
                "version": c.version or "",
                "framework": c.framework or "",
                "source_file": c.file,
            }
            for c in graph.components
        ]
        return components, graph
    except Exception as exc:
        _logger.warning("Component discovery skipped: %s", exc)
        return [], None


def _upload_components(graph, lineaje_pat: str) -> dict:
    """Best-effort upload of the component graph to the Data Service."""
    if not lineaje_pat or graph is None:
        return {}
    try:
        from pipeline.service_integrations.entity_builder import build_aientity_json
        from pipeline.service_integrations.tarball import (
            TarballUploadContext, build_entity_s3_path, create_tarball,
        )
        from pipeline.service_integrations.scim_client import get_presigned_url, upload_to_s3
        from pipeline.foundation.env_defaults import env_get
        from config import DEFAULT_SCIM_SERVICE_URL, DEFAULT_S3_BUCKET
        import uuid

        scim_url = env_get("SCIM_SERVICE_URL", default=DEFAULT_SCIM_SERVICE_URL)
        s3_bucket = env_get("S3_BUCKET", default=DEFAULT_S3_BUCKET)
        ctx = TarballUploadContext(
            bearer_token=lineaje_pat,
            scim_service_url=scim_url,
            s3_bucket_name=s3_bucket,
            unique_id=str(uuid.uuid4()),
        )
        entity_json = build_aientity_json(graph, unique_id=ctx.unique_id)
        if not entity_json:
            return {"uploaded": False, "reason": "no_entities"}
        tarball = create_tarball(entity_json, "entities.aientity.json")
        try:
            s3_path = build_entity_s3_path(ctx)
            presigned = get_presigned_url(scim_url, s3_bucket, s3_path, method="PUT", bearer_token=lineaje_pat)
            if presigned:
                upload_to_s3(tarball, presigned)
                return {"uploaded": True, "s3_path": s3_path, "entity_count": len(entity_json)}
            return {"uploaded": False, "reason": "no_presigned_url"}
        finally:
            try:
                tarball.unlink(missing_ok=True)
            except Exception:
                pass
    except Exception as exc:
        _logger.warning("Component upload skipped: %s", exc)
        return {"uploaded": False, "reason": str(exc)}


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="UniFAI Guardrail Repo Scanner (CON-2014)")
    ap.add_argument("--repo", help="owner/repo on the SCM provider")
    ap.add_argument("--branch", default="main", help="Branch to scan (default: main)")
    ap.add_argument("--local-path", help="Path to an already-cloned repo (skips clone)")
    ap.add_argument("--tenant-id", default="", help="GR service tenant ID")
    ap.add_argument("--company-id", default="", help="GR service company ID")
    ap.add_argument("--provider", default="", help="SCM provider: github|bitbucket|gitlab")
    ap.add_argument("--lineaje-pat", default="", help="Lineaje PAT (GR service auth + Data Service upload)")
    ap.add_argument("--no-pr", action="store_true", help="Skip PR creation — report only")
    ap.add_argument("--dry-run", action="store_true", help="Don't commit or open a PR")
    args = ap.parse_args()

    provider = (args.provider or os.environ.get("SCM_PROVIDER", "github")).lower()
    token = os.environ.get("SCM_ACCESS_TOKEN", "")
    tenant_id = args.tenant_id or os.environ.get("GR_TENANT_ID", "")
    company_id = args.company_id or os.environ.get("GR_COMPANY_ID", "")
    lineaje_pat = args.lineaje_pat or os.environ.get("LINEAJE_PAT", "")

    if not args.local_path and not args.repo:
        _logger.error("Provide --repo or --local-path")
        return 2

    if not args.local_path and not token:
        _logger.error("SCM_ACCESS_TOKEN not set")
        return 2

    with tempfile.TemporaryDirectory(prefix="unifai-gr-repo-") as tmp:
        if args.local_path:
            clone_dir = args.local_path
            head_sha = _git_head_sha(clone_dir) if not args.no_pr else "local"
        else:
            clone_dir = os.path.join(tmp, "repo")
            try:
                _git_clone(args.repo, args.branch, clone_dir, token, provider)
            except subprocess.CalledProcessError as exc:
                _logger.error("Clone failed: %s", exc.stderr.decode(errors="replace") if exc.stderr else exc)
                return 1
            head_sha = _git_head_sha(clone_dir)

        # ── Guardrail stub scan ───────────────────────────────────────────────
        _logger.info("Scanning %s for insertion points …", clone_dir)
        # No policy_map passed — see guardrail_stub_insertion.py's matching
        # comment: the only broad candidate-policy source available today
        # (hardcoded_insertion_point_map()) maps ~49-52 near-identical policy
        # IDs to almost every insertion_point, which would bloat every
        # generated stub with a long, low-signal literal rather than a
        # genuinely precise per-site candidate set.
        candidates, _middleware_candidates = scan_project(project_root=clone_dir, lineaje_pat=lineaje_pat)

        # scan_project always returns c.file as an ABSOLUTE path — normalize
        # to repo-relative here (the single point every caller below routes
        # through) since _apply_stubs / the SCM commit path both need a
        # repo-relative path, not a local clone filesystem path.
        for c in candidates:
            if os.path.isabs(c.file):
                c.file = os.path.relpath(c.file, clone_dir)

        # Deduplicate
        seen: set = set()
        unique: list = []
        for c in candidates:
            key = (c.file, c.line)
            if key not in seen:
                seen.add(key)
                unique.append(c)

        # ── AI Component Discovery ────────────────────────────────────────────
        _logger.info("Running AI component discovery …")
        discovered_components, comp_graph = _discover_components(clone_dir)
        _logger.info(
            "Discovered %d AI component(s) (%s)",
            len(discovered_components),
            ", ".join(f"{c['name']} ({c['type']})" for c in discovered_components[:5])
            or "none",
        )

        # Best-effort upload to Data Service
        component_upload = _upload_components(comp_graph, lineaje_pat)
        if component_upload.get("uploaded"):
            _logger.info("Component inventory uploaded to %s", component_upload.get("s3_path"))

        if not unique:
            _logger.info("No unguarded insertion points found — nothing to do.")
            print(json.dumps({
                "status": "clean",
                "violations": 0,
                "discovered_components": discovered_components,
                "component_upload": component_upload,
            }))
            return 0

        files_hit = len({c.file for c in unique})
        _logger.info("Found %d insertion point(s) across %d file(s)", len(unique), files_hit)

        table = _make_table(unique)
        print(f"\n{table}\n")

        if args.no_pr or args.dry_run:
            print(json.dumps({
                "status": "violations_found",
                "violations": len(unique),
                "files": files_hit,
                "discovered_components": discovered_components,
                "component_upload": component_upload,
            }))
            return 0

        # ── Apply stubs ───────────────────────────────────────────────────────
        changed = _apply_stubs(unique, clone_dir)
        if not changed:
            _logger.warning("No files modified after stub application")
            return 1

        # ── Create branch + commit via SCM API ────────────────────────────────
        scm = create_scm_client(provider, token=token)
        stub_branch = f"{_STUB_BRANCH_PREFIX}-{head_sha}"

        # Check if branch already exists
        if scm.branch_exists(args.repo, stub_branch):
            _logger.info("Branch %s already exists — will reuse", stub_branch)
        else:
            scm.create_branch(args.repo, stub_branch, from_sha=head_sha)
            _logger.info("Created branch %s", stub_branch)

        # Commit each changed file
        committed: list[str] = []
        failed: list[str] = []
        for rel_path, new_content in changed.items():
            try:
                blob_sha = scm.get_file_blob_sha(args.repo, rel_path, stub_branch)
                scm.commit_file(
                    repo=args.repo,
                    path=rel_path,
                    content=new_content,
                    branch=stub_branch,
                    message=f"chore(guardrails): add guardrail_check stubs to {rel_path}",
                    sha=blob_sha,
                )
                committed.append(rel_path)
                _logger.info("Committed stubs for %s", rel_path)
            except Exception as exc:
                _logger.warning("Failed to commit %s: %s", rel_path, exc)
                failed.append(rel_path)

        if not committed:
            _logger.error("No files committed — aborting PR creation")
            return 1

        # ── Open PR ───────────────────────────────────────────────────────────
        components_section = _make_components_section(discovered_components)
        pr_body = _BOT_PR_BODY_TEMPLATE.format(
            marker=_COMMENT_MARKER,
            count=len(unique),
            files=files_hit,
            table=table,
            components_section=components_section,
            tenant_id=tenant_id or "<set GR_TENANT_ID>",
        )

        existing_pr = scm.find_open_pr_by_prefix(
            args.repo, head_prefix=_STUB_BRANCH_PREFIX, base=args.branch,
        )
        if existing_pr:
            scm.update_pull_request_body(args.repo, existing_pr, body=pr_body)
            pr_number = existing_pr
            _logger.info("Updated existing PR #%d", pr_number)
        else:
            pr_number = scm.create_pull_request(
                repo=args.repo,
                head=stub_branch,
                base=args.branch,
                title=_PR_TITLE_TEMPLATE.format(count=len(unique)),
                body=pr_body,
            )
            _logger.info("Opened PR #%d", pr_number)

        result = {
            "status": "pr_opened",
            "pr_number": pr_number,
            "branch": stub_branch,
            "violations": len(unique),
            "files_modified": len(committed),
            "files_failed": len(failed),
            "discovered_components": discovered_components,
            "component_upload": component_upload,
        }
        print(json.dumps(result, indent=2))
        return 0


if __name__ == "__main__":
    sys.exit(main())
